COURSE_ACTS(COURSE_BOB, _(" 1 CAMP DELS BOB-OMB"),
       _("GRAN BOB-OMB AL CIM")     , _("CURSA AMB KOOPA EL Rう PID") , _("LLENけ A'T A L'ILLA AL CEL"),
       _("CERCA LES 8 MONEDES ROGES")          , _("MARIO, A VOLAR!")        , _("ALLIBERA EL CHOMP CADENES"))

COURSE_ACTS(COURSE_WF, _(" 2 FORTALESA D'EN WHOMP"),
       _("DERROCA EN WHOMP")        , _("Vえ S AL CIM DE LA FORTALESA")    , _("LLENけ A'T A CEL OBERT"),
       _("MONEDES ROGES A LES ILLES FLOTANTS"), _("CAIGUDA LLIURE A L'ILLA DE LA Gう BIA")    , _("A COP DE CANか  CONTRA EL MUR"))

COURSE_ACTS(COURSE_JRB, _(" 3 BADIA PIRATA "),
       _("EL BOTお  DEL VAIXELL ENFONSAT")    , _("POT L'ANGUILA SORTIR A JUGAR?") , _("TRESOR A LA COVA DE L'OCEう "),
       _("MONEDES ROGES AL VAIXELL FLOTANT")  , _("APUNTA AL Mえ S ALT DE L'AGULLA")     , _("A CONTRACORRENT"))

COURSE_ACTS(COURSE_CCM, _(" 4 MUNTANYA Gへ LIDA"),
       _("LLISCA LLISCANT PEL TOBOGAN")             , _("PETIT PINGく お  PERDUT")             , _("EL Mえ S Rう PID DEL GEL"),
       _("Gへ LIDA BAIXADA DE LES MONEDES ROGES")  , _("NINOT DE NEU SENSE CAP")       , _("BOTA I REBOTA A LA PARET"))

COURSE_ACTS(COURSE_BBH, _(" 5 MANSIか  DELS BOO"),
       _("CAけ AFANTASMES")            , _("ELS CAVALLETS DEL GRAN BOO") , _("EL SECRET DELS LLIBRES ENCANTATS"),
       _("CERCA LES ESGARRIFOSES 8 MONEDES ROGES")          , _("EL BALCか  DEL GRAN BOO")             , _("HABITACIか  SECRETA AMB CARA I ULLS"))

COURSE_ACTS(COURSE_HMC, _(" 6 COVA DEL LABERINT"),
       _("EL MONSTRE DEL LLAC SUBTERRANI")  , _("ELEVA'T PER LES 8 MONEDES ROGES")       , _("MARIO, L'HOME D'ACER!"),
       _("NAVEGANT EL LABERINT Tほ XIC")     , _("L'ALTRA SORTIDA DEL LABERINT")     , _("COMPTE AMB LES ROQUES RODANTS!"))

COURSE_ACTS(COURSE_LLL, _(" 7 TERRA DE LA LAVA"),
       _("BULL EL GRAN BULLY")            , _("A LA CAけ A DELS BULLY'S")             , _("EL PUZLE DE LES 8 MONEDES ROGES"),
       _("EL TRONC INCANDESCENT")           , _("AL COR DEL VOLCう ")  , _("PLATAFORMA VOLADORA DEL VOLCう "))

COURSE_ACTS(COURSE_SSL, _(" 8 TERRA DE LES ARENES"),
       _("A LES URPES DE LA GRAN AU") , _("AL Mえ S ALT DE LA PIRう MIDE")      , _("EL SECRET DE LA PIRう MIDE"),
       _("CORONA ELS QUATRE PILARS"), _("VOLA LLIURE A PER LES MONEDES ROGES")   , _("EL LABERINT DE LA PIRう MIDE"))

COURSE_ACTS(COURSE_DDD, _(" 9 MOLL TENEBRか S"),
       _("SOBRE EL SUBMARお  D'EN BOWSER")            , _("A COFRE-CORRENT")         , _("8 MONEDES ROGES DE PAL EN PAL"),
       _("A CONTRACORRENT")        , _("RERE L'ESTELA DE LA RAJADA")        , _("COL&LECCIONA ELS BARRETS..."))

COURSE_ACTS(COURSE_SL, _("10 TERRA NINOT DE NEU"),
       _("SOBRE EL CAP DEL NINOT DE NEU")            , _("REFRESCA EL BULLY")          , _("DINS DEL GLAけ か "),
       _("EL REMOLお  DE L'ESTANY GELAT")  , _("SURFEJANT PER LES 8 MONEDES ROGES") , _("DINS L'IGLき "))

COURSE_ACTS(COURSE_WDW, _("11 VILA XOPA-SECA"),
       _("MULLANT PLATAFORMES!")         , _("AL Mえ S ALT DE LA VILA")               , _("SECRETS A LES TORRES I AL CEL"),
       _("ASCENSOR EXPRえ S, AFANYA'T!")   , _("LES 8 MONEDES ROGES DE LA VILA")      , _("CURSA Rう PIDA PER LA VILA!"))

COURSE_ACTS(COURSE_TTM, _("12 MUNTANYA BEN ALTA"),
       _("ESCALA LA MUNTANYA")            , _("EL MISTERI DE LA Gう BIA DEL MICO")    , _("8 MONEDES ROGES A XAMPINYONS ROJOS"),
       _("EL MISTERIか S COSTAT DE LA MUNTANYA")       , _("LA IMPRESSIONANT VISTA DES DEL PONT") , _("DISPARA'T AL XAMPINYか  SOLITARI"))

COURSE_ACTS(COURSE_THI, _("13 PETITA-GRAN ILLA"),
       _("SENSE POR CONTRA LES PLANTES PIRANYA")      , _("AL CIM DE L'ILLA GEGANT"), _("LA REVENJA D'EN KOOPA EL Rう PID"),
       _("ELS CINC PETITS SECRETS DE L'ILLA")       , _("LES 8 MONEDES ROGES DE LA FLORUGA")           , _("BATALLA DINS LA MUNTANYA!"))

COURSE_ACTS(COURSE_TTC, _("14 RELLOTGE TIC-TAC"),
       _("ENGABIA'T A LA Gう BIA!")            , _("EL FOSSAR I ELS Pへ NDULS")     , _("UN COP DE Mう "),
       _("PICA LA ROCA PICUDA")           , _("SALTS MESURATS SOBRE BARRES Mほ BILS")    , _("ATURA EL TEMPS PER 8 MONEDES ROGES"))

COURSE_ACTS(COURSE_RR, _("15 L'ARC DE SANT MARTお "),
       _("CREUER DE L'ARC DE SANT MARTお ")  , _("LA MANSIか  CELESTIAL")      , _("LES 8 MONEDES ROGES DEL LABERINT VERTICAL"),
       _("GRONXANT-SE A LA BRISA")        , _("EL TRUC DE LES PIRう MIDES")             , _("ALGUN LLOC SOBRE L'ARC DE SANT MARTお "))

SECRET_STAR(COURSE_BITDW, _("   BOWSER A LES TENEBRES"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER AL MAR DE FOC"))
SECRET_STAR(COURSE_BITS, _("   BOWSER AL CEL"))
SECRET_STAR(COURSE_PSS, _("   EL TOBOGAN SECRET DE LA PRINCESA"))
SECRET_STAR(COURSE_COTMC, _("   CAVERNA OF DEL BARRET METう L&LIC"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE DEL BARRET ALAT"))
SECRET_STAR(COURSE_VCUTM, _("   BARRET ESVAみ T SOTA EL FOSSAR"))
SECRET_STAR(COURSE_WMOTR, _("   MARIO VOLADOR A L'ARC DE SANT MARTお "))
SECRET_STAR(COURSE_SA, _("   L'AQUARI SECRET"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   ESTRELLES SECRETES"))

EXTRA_TEXT(0, _("UNA DE LES ESTRELLES SECRETES DEL CASTELL!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
 
